version: "3.9"

services:
  dengue-dashboard:
    build: https://github.com/momustafahmed/dengue-thailand-ews.git
    ports:
      - "8501:8501"
    environment:
      STREAMLIT_ENV: production
    restart: unless-stopped
